services:
  frontend:
    image: node:24-alpine
    container_name: niu_code_frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app:delegated
      - type: volume
        source: frontend_node_modules
        target: /app/node_modules
        volume:
          nocopy: true
    command: >
      sh -c "
        yarn install &&
        yarn dev
      "
    ports:
      - '5173:5173'
    networks:
      - app_network
    depends_on:
      - backend
  backend:
    image: ghcr.io/astral-sh/uv:debian
    container_name: app_backend
    working_dir: /app
    volumes:
      - ./backend:/app:delegated
      - type: volume
        source: backend_venv
        target: /app/.venv
        volume:
          nocopy: true
    ports:
      - '5001:5001'
    environment:
      UV_LINK_MODE: copy
    command: >
      sh -c "
        uv run main.py
      "
    networks:
      - app_network
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: niu_code_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_DATABASE: "niu_code"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app_network
    healthcheck:
      test: mysql --user=root --password=123456789 --execute="SHOW DATABASES;"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  db_data:
  frontend_node_modules:
  backend_venv:
networks:
  app_network:
    driver: bridge